### ISSUE TITLE
Question - It's possible to extract pages and text from the pdf?

### ISSUE THREAD

**Issue by JuanjoA** [preciz/pdf_info#29]
Hello, I am trying your library buy I can't extract text from the pdf pages.
With python pypdf and same pdf I can extract the text.

Is this function possible with the current version of the library?

Thanks!

**Comment by preciz** [comment]
This library is only for getting metadata with regex out of PDFs.
This is useful if the parsing of the PDF failed with other tools, or if you want to see all historic metadata
due to multiple updates to the PDF.

You need to use other tools to get text out of the pages.

**Comment by JuanjoA** [comment]
Thanks @preciz !
